language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-tests-database.sh affilicious_theme_test root '' localhost
  - bash bin/install-tests.sh affilicious_theme_test root '' localhost $WP_VERSION true

script: phpunit
